app:
  mode: scheduler
  task_timeout: 3600
  notification:
    notify_on_startup: false
    notify_on_shutdown: false
web:
  host: 0.0.0.0
  port: 8080
  debug: false
logging:
  level: INFO
  file: logs/maa_scheduler.log
  max_size: 10MB
  backup_count: 5
resource_groups:
- name: redroid
  description: ''
  max_concurrent: 1
- name: default
  description: 默认资源组
  max_concurrent: 1
