app:
  mode: scheduler
  notification:
    notify_on_shutdown: false
    notify_on_startup: false
  task_timeout: 3600
logging:
  backup_count: 5
  file: logs/maa_scheduler.log
  level: INFO
  max_size: 10MB
resource_groups:
- description: 默认资源组
  max_concurrent: 1
  name: default
- description: 摄像头/模拟器相关任务
  max_concurrent: 1
  name: camera
scheduler:
  max_workers: 4
  task_timeout: 3600
web:
  debug: false
  host: 127.0.0.1
  port: 8080
