tasks:
- id: test-console-task
  name: 控制台测试任务
  description: 简单的控制台命令测试
  enabled: true
  priority: 5
  resource_group: default
  main_command: echo '控制台任务执行成功' && date
  enable_adb_wakeup: false
  enable_global_log: true
  enable_temp_log: true
  trigger:
    trigger_type: interval
    interval_minutes: 5
  post_task:
    log_keywords: []
    push_notification:
      enabled: false
      on_success: false
      on_failure: false
- id: test-maa-task
  name: 肉鸽 Sami
  description: ''
  enabled: true
  priority: 3
  resource_group: redroid
  main_command: adb -s localhost:35555 shell am start -n com.hypergryph.arknights/com.u8.sdk.U8UnityContext
    ; sleep 3 ; /root/.cargo/bin/maa roguelike Sami -v
  enable_adb_wakeup: true
  adb_device_id: 127.0.0.1:35555
  enable_global_log: true
  enable_temp_log: true
  trigger:
    trigger_type: scheduled
    start_time: 04:00
    end_time: 03:00
  post_task:
    log_keywords: []
    push_notification:
      enabled: true
      on_success: false
      on_failure: true
      title: MAA任务执行失败
      tag: MAA
      content: MAA任务 {task_name} 执行失败，请检查设备状态
